- name: Install basic tools
  yum: name={{ item }} state=present
  with_items:
    - net-tools
    - bridge-utils
    - httpd-tools
    - vim
    - wget
    - telnet
    - whois
    - tree
    - redhat-lsb
    - screen
    - nc
    - tmux
    - bash-completion

- name: Install dev tools
  yum: name={{ item }} state=present
  with_items:
    - kernel-devel
    - gcc
    - gcc-c++
    - glibc
    - rpm-build
    - make
    - cmake
    - automake
    - autoconf
    - patch
    - libgcc
    - libtool

- name: Install sa tools
  yum: name={{ item }} state=present
  with_items:
    - htop
    - iftop
    - iotop
    - nmap
    - nc
    - lsof
